// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA12tn7cQp88XT1rgEl9NDYuFIt8WuvMf4',
    appId: '1:281372583656:web:ea2837f0f39e782db10b5d',
    messagingSenderId: '281372583656',
    projectId: 'socialmediaapp-8f7dd',
    authDomain: 'socialmediaapp-8f7dd.firebaseapp.com',
    storageBucket: 'socialmediaapp-8f7dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD051KA85crFI62LSBnKzSaB_6GmwANdv0',
    appId: '1:281372583656:android:d9eba3bf9c8e8f6db10b5d',
    messagingSenderId: '281372583656',
    projectId: 'socialmediaapp-8f7dd',
    storageBucket: 'socialmediaapp-8f7dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYIghKGsVk40S_hkVNZiFpUlxAw8J875U',
    appId: '1:281372583656:ios:9f07a75513bf8b34b10b5d',
    messagingSenderId: '281372583656',
    projectId: 'socialmediaapp-8f7dd',
    storageBucket: 'socialmediaapp-8f7dd.appspot.com',
    iosClientId: '281372583656-5dvkg47ourfme828c44nrm6fjk6tt02k.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYIghKGsVk40S_hkVNZiFpUlxAw8J875U',
    appId: '1:281372583656:ios:ff34c58de122de5ab10b5d',
    messagingSenderId: '281372583656',
    projectId: 'socialmediaapp-8f7dd',
    storageBucket: 'socialmediaapp-8f7dd.appspot.com',
    iosClientId: '281372583656-evlt1f097jakg9vefgqospgd0tm8jqgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMedia.RunnerTests',
  );
}
